version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-admin-panel
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build: .
    container_name: fastapi-admin-panel
    env_file:
      - ./.env
    environment:
      - MONGODB_URL=${MONGODB_URL}
    ports:
      - '8000:8000'
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo:

networks:
  app-network:
    driver: bridge
